- .github/workflows/pack.yml
- .github/workflows/release.yml
This PR adds the CI step to publish a new version on NPM and fixes #4 .
> Complete CI with NPM publish

- .typescript/tsconfig.build.json
- src/components/Icon/index.stories.tsx
- src/components/Icon/utils.tsx
- src/index.ts
- src/types/Icon.ts
- src/utils/storybook.jsx
This PR adds new icons for the Icon component and defines the Icon component story.
It fixes #30 .
> Enrich Icon Set

- .github/workflows/release.yml
This PR adds `prettify` command on CI.
> Prettier on CI

- src/components/Switch/index.stories.tsx
- src/components/Switch/index.test.tsx
- src/components/Switch/index.tsx
- src/types/Switch.ts
- src/utils/FormMock.tsx
This PR fixes #28 adding the `Switch` component
> Switch component

- src/components/Button/index.stories.tsx
- src/components/Button/index.tsx
- src/types/Button.ts
> Add property "disabled" to Button component

- src/components/InputNumber/index.stories.tsx
- src/components/InputNumber/index.test.tsx
- src/components/InputNumber/index.tsx
- src/components/InputText/index.stories.tsx
- src/components/InputText/index.test.tsx
- src/components/InputText/index.tsx
- src/components/Switch/index.test.tsx
- src/components/Switch/index.tsx
- src/types/Input.ts
- src/utils/mocks/IntlProviderMock.tsx
This PR fixes #55.
Ref issue #71.
> 55 intl all components

- src/components/Checkbox/index.stories.tsx
- src/components/Checkbox/index.test.tsx
- src/components/Checkbox/index.tsx
- src/index.ts
- src/types/Checkbox.ts
- src/utils/mocks/IntlProviderMock.tsx
This PR fixes #3  adding the `Checkbox` component.
> Implement Checkbox

- src/index.ts
This PR fixes #81 adding external export for internationalized components.
> Add external export for internationalized components

- src/components/Typography/index.stories.tsx
- src/components/Typography/index.tsx
- src/index.ts
- src/types/Typography.ts
This PR close #84 adding `display` property to `Typography` component
> Add display property to Typography component

- LICENSE
- package.json
> Include open source license

- src/components/IconButton/index.stories.tsx
- src/components/IconButton/index.test.tsx
- src/components/IconButton/index.tsx
- src/types/IconButton.ts
This PR fixes #69 adding the `IconButton` component
> IconButton component

- src/components/AppBar/index.stories.tsx
- src/components/AppBar/index.tsx
- src/components/AppBar/styled.tsx
- src/components/Icon/utils.tsx
- src/types/AppBar.ts
- src/types/Icon.ts
- src/utils/index.ts
This PR adds some features tot the AppBar component, in particular:
- title now can be clicked
- handling of multiple actions
- user menu
A preview from storybook:
> AppBar component improvements

- src/utils/stories/CustomDocsPage.jsx
- src/utils/stories/utils.tsx
This PR fixes #122 adjusting the imports path in documentation
> Fix imports in Docs

- .github/workflows/release.yml
✅ Closes: 127
This PR adds a dedicated build step in release.yml file
> Added dedicated build step in release CI

- .github/workflows/release.yml
- .releaserc.json
This PR adds some CI improvements and closes #127  and #129 .
Now commits of type ci, chore and perf will trigger a patch release.
Added ESLint processing in the code format step.
> CI Bundle of improvements

- package-lock.json
- package.json
This PR fixes #139 and fixes #140 adjusting some dependencies in `package.json`.
> Package dependencies fixes

- src/components/Icon/utils.tsx
- src/types/Icon.ts
> Add Power Icon

- .vscode/settings.json
- src/components/AppBar/index.stories.tsx
- src/components/AppBar/index.test.tsx
- src/components/AppBar/index.tsx
- src/components/AppBar/styled.tsx
- src/types/AppBar.ts
This PR fixes #158 adding username in AppBar component.
> Add username in AppBar

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
- src/types/Table.ts
This PR fixes #157 adding First/Last button in Table pagination.
> Add First/Last button in Table Pagination

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
This PR fixes #156 adding multiple selection in Table.
> Add multiple selection in Table

- .vscode/settings.json
- src/components/AppBar/index.stories.tsx
- src/components/AppBar/index.test.tsx
- src/components/AppBar/index.tsx
- src/components/AppBar/styled.tsx
- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
- src/types/AppBar.ts
This RC:
- fixes #156 in PR #162 
- fixes #157 in PR #159 
- fixes #158 in PR #160
> Release Candidate

- src/components/Checkbox/__snapshots__/index.test.tsx.snap
- src/components/Checkbox/index.stories.tsx
- src/components/Checkbox/index.test.tsx
- src/components/Checkbox/index.tsx
- src/components/Switch/__snapshots__/index.test.tsx.snap
- src/components/Switch/index.stories.tsx
- src/components/Switch/index.test.tsx
- src/components/Switch/index.tsx
- src/components/Table/__snapshots__/index.test.tsx.snap
- src/types/Checkbox.ts
- src/types/Switch.ts
This PR closes #172 and closes #97 adding label and labelPlacement to `Checkbox` and `Switch` components.
> Add labels to Checkbox and Switch

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/components/HeadCell/index.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
- src/components/Table/utils.ts
- src/types/Table.ts
This PR closes #186 and closes #188.
> [Table] Change internal id & sort columns

- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
> [Select] Preserve group by order

- src/components/AppBar/index.stories.tsx
- src/components/AppBar/index.test.tsx
- src/components/AppBar/index.tsx
- src/components/Menu/index.tsx
- src/types/AppBar.ts
- src/types/Menu.ts
> [AppBar] Add locales handling

- src/components/Modal/index.stories.tsx
- src/components/Modal/index.test.tsx
- src/components/Modal/index.tsx
- src/types/Modal.ts
> [Modal] Add fullscreen size

- CONTRIBUTING.md
Updated Contributing to add notes on how to branch.
> Updated Contributing

- CONTRIBUTING.md
- README.md
- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/components/HeadCell/index.tsx
- src/components/Table/components/Pagination/index.tsx
- src/components/Table/components/PaginationActions/index.tsx
- src/components/Table/components/ToolbarAction/index.tsx
- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
- src/types/Base.ts
- src/types/Table.ts
- src/utils/index.ts
This PR closes #205 and closes #103.
> [Table] Custom page size & Icon actions

- src/components/Table/components/Pagination/index.tsx
- src/components/Table/index.test.tsx
fix: 🐛 [Table] Fixed page out of range in MUITablePagination
✅ Closes: #208
> Fixed page out of range in MUITablePagination

- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
- src/types/Select.ts
feat: 🎸 [Select] Added onScroll listener and scrollEnd callback
It is now possible to attach onScrollEnd callback to onScroll event.
✅ Closes: #207
> [Select] Added onScroll listener and scrollEnd callback

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
fix: 🐛 [Table] Hidden actions not rendered anymore …
Closes: #211
> [Table] Table hidden actions

- src/components/Select/index.stories.tsx
- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
- src/types/Select.ts
feat: 🎸 [Select] Added onInputChange callback
It is now possible to get a callback fired whenever the input value
changes
✅ Closes: #213
> [Select] Added onInputChange callback

- src/components/Select/index.stories.tsx
- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
- src/types/Select.ts
feat: 🎸 [Select] Added onClose property
✅ Closes: #215
> [Select] Added onClose property

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/components/ToolbarAction/index.tsx
- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
- src/types/Table.ts
feat: 🎸 [Table] Row actions can be disabled based on data
Actions defined as TableActionPosition.row can now evaluate disabled
flag based on row data
✅ Closes: #219
> [Table] Row actions can be disabled based on data

- .storybook/preview.js
- src/types/InputText.ts
docs: ✏️ [StoryBook] Publish docs only
fix: 🐛 [InputText] Restore type of onChange property
> Storybook upgrade fixes

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/components/ToolbarAction/index.tsx
- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/types/Table.ts
feat: 🎸 [Table] Actions to be disabled based on data selection
Disabled function accepts data[] as item to evaluate
✅ Closes: 231
> [Table] Actions to be disabled based on data selection 

- .github/workflows/release.yml
Update release.yml to count untracked files
> Update release.yml to count untracked files

- src/components/AppBar/__snapshots__/index.test.tsx.snap
- src/components/AppBar/components/Actions/index.tsx
- src/components/AppBar/components/Content/index.tsx
- src/components/AppBar/components/Title/index.tsx
- src/components/AppBar/index.stories.tsx
- src/components/AppBar/index.test.tsx
- src/components/AppBar/index.tsx
- src/types/AppBar.ts
This PR closes #244 :
[feat: 🎸 [AppBar] Custom children has precedence over title]
[docs: ✏️ [AppBar] Updated docs]
[test: 💍 [AppBar] Updated tests]
[refactor: 💡 [AppBar] Complete code refactor using hooks]
[docs: ✏️ [AppBar] Updated docs]
> [AppBar] Custom children with precedence over title

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/components/ActionsCell/index.tsx
- src/components/Table/components/DataCell/index.tsx
- src/components/Table/components/Head/index.tsx
- src/components/Table/components/HeadCell/index.tsx
- src/components/Table/components/Loader/index.tsx
- src/components/Table/components/RowAction/index.tsx
- src/components/Table/components/SelectionCell/index.tsx
- src/components/Table/components/Toolbar/index.tsx
- src/components/Table/index.stories.tsx
- src/components/Table/index.tsx
- src/components/Table/utils.ts
- src/types/Table.ts
This PR closes #289.
It removes sticky constraint for checkbox and primary action, plus setting this order:
checkbox / primary-actions / data / row-actions
Sticky positioning of checkbox can be set using `stickySelection`.
> [Table] Issues with primary action

- src/components/Modal/index.stories.tsx
- src/utils/mocks/FormMock.tsx
- src/utils/mocks/ModalMock.tsx
This PR closes #312 restoring the open / close toggle on Modal component.
Extra: allows to set state value via args
CC: @CrisGrud
> Fixed Modal storybook

- src/components/Button/__snapshots__/index.test.tsx.snap
- src/components/Button/index.test.tsx
- src/components/Progress/__snapshots__/index.test.tsx.snap
- src/components/Progress/index.stories.tsx
- src/components/Progress/index.test.tsx
- src/components/Progress/index.tsx
- src/types/Progress.ts
> [Progress] Added new component

- src/components/BreadCrumbs/__snapshots__/index.test.tsx.snap
- src/components/BreadCrumbs/index.test.tsx
- src/components/InputNumber/__snapshots__/index.test.tsx.snap
- src/components/InputNumber/index.stories.tsx
- src/components/InputNumber/index.test.tsx
- src/components/InputNumber/index.tsx
- src/components/Progress/__snapshots__/index.test.tsx.snap
- src/components/Progress/index.test.tsx
> [Input Number] Min value fixed

- src/components/Menu/index.stories.tsx
- src/index.ts
- src/types/Menu.ts
> [Menu] Added component

- src/components/BreadCrumbs/index.tsx
> [BreadCrumbs] Fixed "key" error

- src/components/Stepper/__snapshots__/index.test.tsx.snap
- src/components/Stepper/index.stories.tsx
- src/components/Stepper/index.test.tsx
- src/components/Stepper/index.tsx
- src/types/Stepper.ts
- src/utils/mocks/StepperMock.tsx
> [Stepper] Add new component

- src/components/BreadCrumbs/index.stories.tsx
- src/components/DateTimePicker/index.stories.tsx
- src/components/ModalWithTabs/index.stories.tsx
- src/components/SelectVirtualized/index.stories.tsx
- src/components/Stepper/index.stories.tsx
- src/components/Tabs/index.stories.tsx
- src/index.ts
This PR closes #342 and closes #341
> Minor fixes

- src/components/DateTimePicker/index.stories.tsx
- src/components/DateTimePicker/index.tsx
- src/contexts/Mosaic.tsx
- src/types/DateTimePicker.ts
> [DateTimePicker] Added Timezone in context

- package-lock.json
- package.json
- src/components/DateTimePicker/index.test.tsx
- src/components/DateTimePicker/index.tsx
- src/components/ModalWithTabs/index.test.tsx
- src/contexts/Mosaic.tsx
- src/types/DateTimePicker.ts
> [DateTimePicker] Added timeZone prop

- src/components/DateTimePicker/index.tsx
> [DateTimePicker] Fixed input validation

- src/components/DateTimePicker/index.stories.tsx
- src/components/DateTimePicker/index.tsx
- src/types/DateTimePicker.ts
> [DateTimePicker]Changed return value to Date JS

- README.md
- package-lock.json
- src/components/AppBar/index.stories.tsx
- src/components/Button/index.stories.tsx
- src/components/Card/index.stories.tsx
- src/components/Checkbox/index.stories.tsx
- src/components/InputNumber/index.stories.tsx
- src/components/InputText/index.stories.tsx
- src/components/Modal/index.stories.tsx
- src/components/ModalWithTabs/index.stories.tsx
- src/components/ModalWithTabs/index.tsx
- src/components/Select/index.stories.tsx
- src/components/SelectVirtualized/index.stories.tsx
- src/components/SelectVirtualized/index.tsx
- src/components/Switch/index.stories.tsx
- src/components/Table/index.stories.tsx
- src/components/Typography/__snapshots__/index.test.tsx.snap
- src/components/Typography/index.stories.tsx
- src/utils/hocs/localized.tsx
- src/utils/mocks/LocaleMock.tsx
This PR closes #355 and closes #354
> Merge from beta

- src/components/BreadCrumbs/index.stories.tsx
- src/components/BreadCrumbs/index.test.tsx
- src/components/BreadCrumbs/index.tsx
- src/components/DateTimePicker/index.stories.tsx
- src/components/DateTimePicker/index.tsx
- src/components/Stepper/__snapshots__/index.test.tsx.snap
- src/components/Stepper/index.stories.tsx
- src/components/Stepper/index.test.tsx
- src/components/Stepper/index.tsx
- src/types/BreadCrumbs.ts
- src/types/DateTimePicker.ts
- src/types/Stepper.ts
- src/utils/mocks/LocaleMock.tsx
> add localization to datetimepicker stepper breadcrumbs

- src/components/ModalWithTabs/index.tsx
> [ModalWithTabs] fixed grid error

- src/components/AppBar/index.test.tsx
- src/components/DateTimePicker/index.stories.tsx
- src/components/DateTimePicker/index.tsx
- src/types/DateTimePicker.ts
- src/utils/stories/utils.ts
> [DateTimePicke] added prop type

- src/components/Select/index.tsx
> [Select] Warning appear only if value is set

- .storybook/preview.ts
- .storybook/test-runner.ts
- package-lock.json
- package.json
- src/components/AppBar/__snapshots__/index.stories.tsx.snap
- src/components/AppBar/index.stories.tsx
- src/components/Card/__snapshots__/index.stories.tsx.snap
- src/components/Card/index.stories.tsx
- src/components/InputNumber/__snapshots__/index.stories.tsx.snap
- src/components/InputNumber/index.stories.tsx
- src/components/Stepper/__snapshots__/index.stories.tsx.snap
- src/components/Stepper/index.stories.tsx
- src/components/Stepper/index.tsx
> [Stepper] Migrate stories to new format

- .storybook/preview.ts
- .storybook/test-runner.ts
- package-lock.json
- package.json
- src/components/AppBar/__snapshots__/index.stories.tsx.snap
- src/components/AppBar/index.stories.tsx
- src/components/Card/__snapshots__/index.stories.tsx.snap
- src/components/Card/index.stories.tsx
- src/components/InputNumber/__snapshots__/index.stories.tsx.snap
- src/components/InputNumber/index.stories.tsx
This PR closes #375.
CC: @CrisGrud
> Improve test coverage

- .github/workflows/release-beta.yml
- .github/workflows/release.yml
> [CI] Replaced deprecated command set-output

- package-lock.json
- package.json
> [Chore] Review browserlist options

- src/components/ModalWithTabs/index.tsx
- src/components/Tabs/__snapshots__/index.stories.tsx.snap
- src/components/Tabs/index.stories.tsx
- src/components/Tabs/index.tsx
- src/types/Tabs.ts
> [Tabs] Add disabled prop

- src/components/ModalWithTabs/index.stories.tsx
- src/components/Tabs/__snapshots__/index.stories.tsx.snap
- src/components/Tabs/index.stories.tsx
- src/components/Tabs/index.tsx
- src/types/Button.ts
- src/types/Tabs.ts
> [Tabs] Added single tab color

- .github/workflows/release-beta.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- assets/.$release-flowchart.drawio.bkp
- assets/release-flowchart.drawio
This PR fixes #395 removing wait and retry action plugin.
Same workflow runs are quit, only the latest one proceeds.
> [CI] Remove wait and retry feature

- src/components/Select/index.stories.tsx
- src/components/Select/index.tsx
- src/types/Select.ts
> [Selecet]Change autoSort prop

- package-lock.json
- package.json
- src/components/Table/components/Head/index.tsx
- src/components/Table/utils.ts
- src/components/TableVirtualized/__snapshots__/index.stories.tsx.snap
- src/components/TableVirtualized/index.stories.tsx
- src/components/TableVirtualized/index.tsx
- src/index.ts
- src/utils/stories/decorators/TableVirtualized.tsx
Added a new Table component using react-virtuoso for virtualization
✅ Closes: #421
> feat: 🎸 [TableVirtualized] Added new component
