melfore/mosaic

- .github/workflows/default.yml
- README.md
- src/components/Button/index.test.tsx
This PR fixes #6 adding a cache layer on the Mosaic CI for package dependencies.
In this way the CI can execute faster if there are no changes to the `package.json` file.
I've also added the status badge in README file that will reflect latest build status for Mosaic.
I've disabled the failing test for the `Button` component in order to let CI go through all steps. 
I'll use it later for developing other CI features that need a previous step failing, then I'll permanently delete the fake test.
We don't have to worry about number of CI runs triggered, as GitHub automatically handles cache limit and expire.
> GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a …
> Add cache for CI

- CONTRIBUTING.md
- src/components/Button/index.stories.tsx
- src/components/Button/index.tsx
- src/components/Checkbox/index.stories.tsx
- src/components/Icon/index.stories.tsx
- src/components/InputNumber/index.stories.tsx
- src/components/InputNumber/index.tsx
- src/components/InputText/index.stories.tsx
- src/components/InputText/index.tsx
- src/components/Modal/index.stories.tsx
- src/components/Switch/index.stories.tsx
- src/components/Switch/index.tsx
- src/components/Typography/index.stories.tsx
- src/components/Typography/index.tsx
- src/utils/stories/CustomDocsBlocks.tsx
- src/utils/stories/CustomDocsPage.jsx
- src/utils/stories/index.jsx
- src/utils/stories/utils.tsx
This fixes #76 .
Instead of the boilerplate code of the snipped I've decided to create a set of predefined doc blocks to auto generate desired documentation parts.
@masmau: **I've updated snippets to reflect these changes, follow guides inside CONTRIBUTING to update yours so you are aligned**
This is the final output:
<hr>
**Detailed changes explained**
This is the new signature for `getDocsPageStructure` which expects the `name` of the component, a boolean flag `intlSupport` that by default it is true and the `notes` which are null.
```
export const getDocsPageStructure = (name, intlSupport = true, notes = null) => ({
docs: {
page: () => <CustomDocsPage intlSupport={intlSupport} name={name} notes={notes} />,
},
});
```
`CustomDocsPage` is a JSX component (Storybook has no type defs for …
> Improve end user documentation

- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
- src/types/Table.ts
This PR adds row selection in Table component providing the `onSelectionChange` callback.
It also refactors the `TableType` removing the boolean flags to enable events. They were redundant since I can use as flag the check on the callbacks.
Improved `Table` docs and tests (only stubbed to guarantee coverage).
> Add row selection in Table

- .huskyrc
- .prettierignore
- CONTRIBUTING.md
- package-lock.json
- package.json
This PR fixes #60 adding pre-git hooks operations using [husky](https://github.com/typicode/husky).
At the moment the only task run is on pre-push operation (build and tests).
> Add pre-git ops

- package-lock.json
- package.json
- src/components/Avatar/index.stories.tsx
- src/components/Avatar/index.tsx
- src/components/Card/index.stories.tsx
- src/components/Card/index.tsx
- src/components/Typography/index.stories.tsx
- src/components/Typography/index.tsx
- src/types/Avatar.ts
- src/types/Base.ts
- src/types/Card.ts
- src/types/Typography.ts
This PR adds a new base type: `LoadableType`. It extends `BaseType` adding the `loading?: boolean` property.
It is meant to target all data-display components (so excluding theoretically input and user interaction components) that might have a loading status, anticipating the need on projects that will use `@melfore/mosaic` bundle of components.
Currently this new base type applies to:
**Avatar**
**Card**
**Typography**
According to emerging needs it can be extended to other components.
> Make Card component loadable

- package-lock.json
- package.json
- src/components/Avatar/index.stories.tsx
- src/components/Avatar/index.tsx
- src/components/Card/index.stories.tsx
- src/components/Card/index.tsx
- src/components/Icon/index.stories.tsx
- src/components/Icon/index.tsx
- src/components/ListCollapsibleItem/index.stories.tsx
- src/components/ListCollapsibleItem/index.test.tsx
- src/components/ListCollapsibleItem/index.tsx
- src/components/ListItem/index.stories.tsx
- src/components/ListItem/index.test.tsx
- src/components/ListItem/index.tsx
- src/components/Typography/index.stories.tsx
- src/components/Typography/index.tsx
- src/types/Avatar.ts
- src/types/Base.ts
- src/types/Card.ts
- src/types/Icon.ts
- src/types/ListItem.ts
- src/types/Typography.ts
This PR adds two ListItem components that can be combined to render a complex list (using `List` from `@material-ui/core` as wrapper).
**ListItem**
**ListCollapsibleItem**
> Add ListItem components

- src/components/Select/index.stories.tsx
- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
- src/components/Select/styled.ts
- src/types/Select.ts
- src/utils/index.ts
This PR fixes #27 by adding Select component.
It is built upon `Autocomplete` from `@material-ui/lab`, including the following features:
- autocomplete
- customized options (labels and rendering)
- disable state
- groups (with custom labels)
- initialValue provisioning (with validation against multiple selection)
- loading
- multiple selection
Compromise was taken on code coverage: it is now barely acceptable, it performs only rendering tests on several cases with no detailed assertions. Will be implemented later on but however meets predefined thresholds.
> Implement Select component

- src/components/InputText/index.test.tsx
- src/components/Select/index.stories.tsx
- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
- src/components/Select/styled.ts
- src/types/Input.ts
- src/types/Select.ts
This PR extends the features of the Select component done in #118.
In particular:
- makes `Select` always a stateless component (`value` prop should always arrive from outside)
- `Select` extends `BaseInput` type adding all the typical input props
- allows customization of width of the popup (aka `popper`) with `customPopperWidth` prop
- **[most important]** `SelectType` becomes dynamic looking at `multiple` prop
> Select component improvements

- README.md
- src/index.ts
This PR closes #131 adding export for `InputType` enum.
It also adds some more documentation on the migration guide from `0.x` to latest.
> Export InputType enum

- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
This PR fixes #137 adding handling of immutable data in `Select` and `Table` components.
> Immutable data handling

- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
This PR closes #142  fixing the data-cy reference for Select.
The `Autocomplete` component can be spotted using `-outer-wrapper` suffix, while the default `data-cy` refers to the input.
> Fixed data-cy reference for Select

- src/components/InputText/index.stories.tsx
- src/components/InputText/index.test.tsx
- src/components/InputText/index.tsx
- src/types/InputText.ts
- src/utils/index.test.ts
This PR closes #177 removing internal state from `InputText` component.
> Remove internal state from InputText

- README.md
- package.json
- src/components/Avatar/__snapshots__/index.test.tsx.snap
- src/components/Card/__snapshots__/index.test.tsx.snap
- src/types/Avatar.ts
This PR closes #178 removing deprecated `variant="circle"` for `Avatar` component.
> Update Avatar component

- src/types/InputText.ts
fix: 🐛 [InputText] Restore onChange type definition
✅ Closes: #224
> [InputText] Restore onChange type definition

- src/types/Table.ts
Setting callback options to be optional to ensure backward compatibility
> fix: 🐛 [Table] Callback options to be optional

- src/components/Select/components/Group/index.tsx
- src/components/Select/components/Input/index.tsx
- src/components/Select/components/Option/index.tsx
- src/components/Select/components/Popper/index.tsx
- src/components/Select/index.test.tsx
- src/components/Select/index.tsx
[refactor: 💡 [Select] Split Group and Popper components]
refactor: 💡 [Select] Split Input component 
refactor: 💡 [Select] Split Option component 
refactor: 💡 [Select] Code cleaning for inner components 
feat: 🎸 [Select] Display checkbox only when multiple=true
feat: 🎸 [Select] Wrapped each option in a div with dataCy 
[test: 💍 [Select] Updated tests]
Closes #249
> [Select] Separate inner components

- src/components/Adornment/components/Badge/index.tsx
- src/components/Adornment/components/Tooltip/index.tsx
- src/components/Adornment/index.tsx
- src/components/AppBar/components/Actions/index.tsx
- src/components/AppBar/components/Content/index.tsx
- src/components/AppBar/index.stories.tsx
- src/components/AppBar/index.test.tsx
- src/components/AppBar/index.tsx
- src/components/Icon/index.stories.tsx
- src/components/Icon/index.tsx
- src/components/IconButton/__snapshots__/index.test.tsx.snap
- src/components/IconButton/index.stories.tsx
- src/components/IconButton/index.test.tsx
- src/components/IconButton/index.tsx
- src/components/Menu/index.tsx
- src/components/Modal/index.tsx
- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/components/PaginationActions/index.tsx
- src/components/Table/components/RowAction/index.tsx
- src/components/Table/components/Toolbar/index.tsx
- src/components/Table/components/ToolbarAction/index.tsx
- src/types/Adornment.ts
- src/types/Icon.ts
- src/types/IconButton.ts
- src/types/Menu.ts
- src/types/Table.ts
- src/utils/index.ts
This PR adds badge and tooltip features to existing components.
Closes: #258 #167 #169 
Natively supported by `Icon` and `IconButton`, inherited by many others (`AppBar`, `Table` etc..).
Below preview of how it will look like (_all tooltips are exposed and automatically open just for purpose of documenting_).
Native support:
Inherited support:
This PR requires still a bit of extra work before being merged and released due to missing tests and possible improvements / refactorings. Will be released anyhow by the end of the month in the upcoming Mosaic release.
Please share your  ideas and opinions @gabrielepolizzotto-bitrocketdev @erik18xk @erosval
> Add Badge and Tooltip features to components

- src/components/Table/components/Head/index.tsx
- src/components/Table/components/HeadFilter/index.tsx
- src/components/Table/index.stories.mdx
- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
- src/types/Table.ts
This PR enable passing a component to render below the table header 
Filter components are specific for each column and set with the `renderFilter` attribute in columns definition:
```js
columns: [
{ label: "Name", path: "name", renderFilter: <MUITextField type="text" label="type to filter" /> },
{ label: "Age", path: "age" },
],
```
Table component doesn't provide any filter logic and filters are hidden by default. To toggle visibility simply set `showFilters` prop to  `<Table />` accordingly.    
When table has `sticky` header MUI set sticky position at cell level (see `<HeadCell />`).
If filters row is visible, we need to set sticky positioning to the whole table head in order to avoid tracking the actual height of the first header row (which can vary depending on table width and cell …
> [Table] Filter column component

- CHANGELOG.md
- README.md
docs: ✏️ Updated documentation for version bump
BREAKING CHANGE: 🧨 Officially dropped support for versions of React < 18.x and MUI < 5.x
> Updated documentation for version bump

- src/components/ModalWithTabs/index.tsx
- src/components/Tabs/index.tsx
BREAKING CHANGE: 🧨 Renamed `labelList` prop into `tabList` for Tabs. This impacts also ModalWithTabs.
> [Tabs] Renamed `labelList` into `tabList`
